--db/seed.sql
\c menuitems_dev;

INSERT INTO menuitems (name,image_id, category, description, price, out_of_stock, ranking) VALUES ('Arancini', 'Arancini', 'Snack/Street food', 'Italian rice balls that are stuffed, coated with breadcrumbs and deep fried. They are a staple of Sicilian cuisine.', 10.00, False, 10 ), ('Fried Calzone', 'FriedcalzonePanzerotti', 'Savory pie/turnover', 'A calzone is a pizza folded in two and stuffed with various fillings, from ham and cheese to vegetables, ricotta, parmesan, and even eggs.', 12.50, False, 8), ('Pasta fritta', 'friedpasta', 'Pasta/Street food', 'A street food consisting left over pasta with sauce fried with a little olive oil, and grated cheese.', 11.50, False, 10), ('Pane e Panelle', 'Paneepanelle', 'Sandwich/Street food', 'Sicilian panelle are chickpea fritters, commonly served in a sandwich, and simply referred to as pane e panelle (bread and panelle). This street food is especially popular in Palermo, where you can find it virtually anywhere in the city.', 6.50, False, 10 ), ('Pani ca Meusa', 'Panicameusa', 'Sandwich/Street food', 'Pani câ meusa in Sicilian is a unique dish of bread with spleen. This delicacy consists of a soft bun topped with sesame seeds, filled with pieces of veal lung and spleen that have been first boiled then fried in lard.', 8.50, False, 9), ('Stigghiola', 'Stigghiola', 'Street food', 'Stigghiola is a cut of gut, usually, lamb, goat, or chicken, washed and seasoned with onion, parsley, and other herbs, then rolled on top of spring onion. Once prepared and seasoned, stigghiola is grilled and served hot, topped with salt and lemon.', 5.75, False, 8), ('Cannoli', 'Dessert', 'Cannoli', 'Cannoli are basically pastries that are filled with chocolate, cream or sweet ricotta and moulded in the shape of a tube.', 4.50, False, 10),
('Bruschetta con pomodoro', 'Appetizer', 'Bruschetta', 'Bruschetta is an Italian antipasto (appetizer) that was originally created to salvage stale bread and showcase the flavors of olive oil. In Italy, the term “bruschetta” refers to the grilled slice of bread, rubbed with garlic and olive oil, not the topping itself. Tomato and basil are a common bruschetta topping, as well as beans and cured meats.', 3.50, False, 8 ),
('Parigina', 'Stuffed pizza', 'Parigina', 'A sheet pan pizza filled with prosciutto, tomatoes,mozzarella, and topped with filo dough (puff pastry).', 9.50, False, 9), ('Napoleon', 'Dessert', 'Napoleon', 'A napoleon or mille-feuille is a classic French pastry with layers of buttery, flaky puff pastry baked until golden and crisp, then filled with alternating layers of pastry cream and whipped cream.', 6.75, False,10),
('Zeppoles', 'Dessert', 'Zeppoles', 'Zeppole is an Italian donut-type pastry that is classically fried but can also be baked. They can have various fillings like custard, honey, pistaccio cream, almonds, jelly, or ricotta cheese.', 8.00, False, 8),
('Brioche con Gelato', 'Dessert', 'brioche', 'Brioche con gelato is a traditional Italian dessert hailing from Sicily. This dessert sandwich consists of a soft, buttery brioche bun that is stuffed with a generous amount of gelato.', 7.00, False, 10),
('Crocche', 'Street food/snack', 'Crocche', 'Crocchè is a famous Sicilian deep-fried snack. Also known as crocchè di patatte, and panzarotti in Neapolitan, it is made with mashed potatoes, eggs, Parmigiano and mozzarella cheese, and parsley or mint leaves. Additional ingredients occasionally include provolone cheese, prosciutto, and salami.', 5.50, False, 7),
('Polpette di Cavallo', 'Streetfood/snack', 'meatballs', 'Polpette di cavallo is a spin on the classic Italian meatballs, but it contains horse meat (carne di cavallo) instead of veal or beef. This meat specialty is typically prepared with a mixture of ground horse meat, eggs, breadcrumbs, parmesan, parsley, lemon zest, salt, and pepper, which is then shaped into meatballs which are the size of a small mandarin orange.', 6.50, False, 8),
('Pezzi Di Rosticceria', 'Stuffed bread', 'Rosticceria', 'Pezzi are made of brioche dough that have been baked or fried and stuffed with various fillings. One of the more famous would be the Calzone al Forno (baked brioche stuffed with ham and mozzarella).', 5.00, False, 9),
('Pani cunzatu', 'Sandwich', 'PaneCunzato', 'The cunzatu bread, or bread cunzato, is a recipe born out of poverty. Typically made with bread seasoned with olive oil, fresh tomatoes, oregano, anchovies, salt and pepper, cheese, and onions.', 6.25, False, 7);

-- INSERT INTO tweets (menuitem_id, username, image_id, location, time, caption, hashtags) VALUES (1, 'CapricciosFoodTruck', 'timesq', 'Time Square', TO_TIMESTAMP('12:30', 'HH24:MI'), 'Be there or be squared!', '#meatballdrop #CapricciosFoodTruck #timesquareHereWeCome' ), (2, 'CapricciosFoodTruck', 'BronxzooFeed', 'Bronx Zoo', TO_TIMESTAMP('2:00', 'HH24:MI'), 'Its feeding time!!', '#DontFeedTheAnimals #Feedingtime'), (3, 'CapricciosFoodTruck', 'LittleItaly', 'Little Italy', TO_TIMESTAMP('1:00', 'HH24:MI'), 'Back to the motherland', '#Italy #Noflights #EconomyClassLOL #Goodeats #streetfoodfair #SanGennarofeast'), (4, 'xoxosweetiepatootiexoxo', 'Riverfront', 'Front Row Seat: East Riverfront Area', TO_TIMESTAMP('4:00', 'HH24:MI'), 'Hey Capriccios, can you celebrate with us this 4th of July?', '#fireworks, #goodfoodgoodtimes, #Goodeats #Capriccios'), (5, 'CapricciosFoodTruck', 'Greatfoodtruck', 'Food Network', TO_TIMESTAMP('4:30', 'HH24:MI'), 'You got the chops to be the next Great American Food Truck?', '#foodnetwork #foodtruckrace #foodtruckcrosscountry #WeHaveOurselvesACookoff'),(6, 'GrubFinder', 'maxresdefault', 'Somewhere in Brooklyn', TO_TIMESTAMP('7:15', 'HH24:MI'), 'Hey mamma! Whats your 10-4? I want to know what all the fuss is about with your food? Will your food be on point or will you drop the errr.. meat-BALL on your food review?!', '#FoodieAtHeart #TheReviewThatCanNotBeChallenged #NoReviewBoothForThisKindOfReview' ), (7, 'ShrimpNPataters', 'FOODTRUCK', 'Foodtruck Festival', TO_TIMESTAMP('8:00', 'HH24:MI'), 'We heard all the hype about you guys! Here is an invite to the festival. We would be honored to have yall!', '#ShrimpOverEverything #2023FoodtruckFestival #FestivalCookout');

INSERT INTO grubposts (name, location, image_id, message, rating, menuitem_id) VALUES ('Sal', 'Manalapan, NJ', 'image_id', 'These riceballs are just the way my nonna makes them. Perfetto!', 10, 1), ('Jen', 'Brooklyn, NY', 'image_id', 'I bought these thinking they were Onigiri (Japanese riceballs wrapped in seaweed paper). Boy I was surprised. Balls of rice with a meat ragu filling and that  mozzarella pull! That got my mouth watering.', 10, 1), ('Josephine', 'Midlothian, VA', 'image_id', 'OMG! These cannolis are better than any other I have ever tasted! No need to go to another bakery again!', 9, 7), ('Adam', 'Red Bluff, CA', 'image_id', 'I got the sandwich with olive oil, tomato and fresh mozzarella because it reminded me of the times my grandmother would go to the garden and pick tomatoes. Great times!', 8, 16), ('Matt', 'Port St. Lucie, FL','image_id', 'Bruschettas are the ultimate appetizers! I get them at every Italian restaurant. Definitely opens your appetite!', 9, 8), ('Fatima', 'Boston, Massachusetts','image_id', 'Yum, the zeppoles are the bomb!! I get them at every Italian feast! Ya feel me?!', 9, 11), ('Gary', 'Staten Island, NY', 'image_id', 'Fried pasta warms my heart!', 10, 3), ('Giuseppe', 'Torretta, PA', 'image_id', 'Pane con la meusa is just the way I remember it in Italy! Buonissimo!', 8, 5), ('Angelo P.', 'Brooklyn, NY', 'image_id', 'Everytime I see Capriccios food truck! I have to stop by for some Stigghiola! Its outta this world!', 10, 6);
